name = "PortfolioAnalytics"
uuid = "55d897a4-798b-418f-87f2-da98fa5ba518"
authors = ["Mehmet Dogan"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
